# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

socialinterests:
  -
      title: Education
      description: MyText1
      image_url: imag1
      followerscount: 4

  -
      title: Sanitation
      description: MyText2
      image_url: imag2
      followerscount: 5

  -
      title: Food-Donation
      description: MyText3
      image_url: imag3
      followerscount: 13
