# Read about fixtures at http://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html

socialinterests:
  -
      title: Education
      description: MyText
      image_url: MyString
      followerscount: 4

  -
      title: Sanitation
      description: MyText2
      image_url: MyString
      followerscount: 5

  -     
      title: Food-Donation
      description: MyText2
      image_url: MyString
      followerscount: 13
